/*
 * WARNING: this is an autogenerated file and will be overwritten by
 * the extension interface script.
 */
#ifndef APPTRACKERANDROID_AUTODEFS_H
#define APPTRACKERANDROID_AUTODEFS_H

/**
 * string name used to locate this extension
 */
#define S3E_EXT_APPTRACKERANDROID_NAME "AppTrackerAndroid"
#define S3E_EXT_APPTRACKERANDROID_HASH 0x4055eb93

#ifdef S3E_EXT_REGISTER
#ifndef S3E_EXT_REGISTER_KEY
#define S3E_EXT_REGISTER_KEY(name, num, key) S3E_EXT_REGISTER(name, num)
#endif
S3E_EXT_REGISTER("AppTrackerAndroid", 12)
#else

#endif /* S3E_EXT_REGISTER */
#endif /* !APPTRACKERANDROID_AUTODEFS_H */
