/*
 * WARNING: this is an autogenerated file and will be overwritten by
 * the extension interface script.
 */
#ifndef APPTRACKERIOS_AUTODEFS_H
#define APPTRACKERIOS_AUTODEFS_H

/**
 * string name used to locate this extension
 */
#define S3E_EXT_APPTRACKERIOS_NAME "AppTrackeriOS"
#define S3E_EXT_APPTRACKERIOS_HASH 0x41ed49fd

#ifdef S3E_EXT_REGISTER
#ifndef S3E_EXT_REGISTER_KEY
#define S3E_EXT_REGISTER_KEY(name, num, key) S3E_EXT_REGISTER(name, num)
#endif
S3E_EXT_REGISTER("AppTrackeriOS", 13)
#else

#endif /* S3E_EXT_REGISTER */
#endif /* !APPTRACKERIOS_AUTODEFS_H */
