/*
 * WARNING: this is an autogenerated file and will be overwritten by
 * the extension interface script.
 */
/**
 * Definitions for functions types passed to/from s3eExt interface
 */
typedef  s3eResult(*AppTrackeriOSRegister_t)(AppTrackeriOSCallback cbid, s3eCallback fn, void* userData);
typedef  s3eResult(*AppTrackeriOSUnRegister_t)(AppTrackeriOSCallback cbid, s3eCallback fn);
typedef  s3eResult(*AppTrackeriOS_startSession_t)(const char* apiKey);
typedef  s3eResult(*AppTrackeriOS_closeSession_t)();
typedef  s3eResult(*AppTrackeriOS_event_t)(const char* eventName);
typedef  s3eResult(*AppTrackeriOS_eventWithValue_t)(const char* eventName, const char* valueString);
typedef  s3eResult(*AppTrackeriOS_loadModule_t)(const char* location);
typedef  s3eResult(*AppTrackeriOS_loadModuleToCache_t)(const char* location_code);
typedef  s3eResult(*AppTrackeriOS_destroyModule_t)();
typedef  s3eResult(*AppTrackeriOS_fixAdOrientation_t)(int landscape_portrait_or_auto);
typedef  s3eResult(*AppTrackeriOS_setAgeRange_t)(const char* ageRange);
typedef  s3eResult(*AppTrackeriOS_setGender_t)(const char* gender);
typedef       bool(*AppTrackeriOS_isAdReady_t)(const char* placement);

/**
 * struct that gets filled in by AppTrackeriOSRegister
 */
typedef struct AppTrackeriOSFuncs
{
    AppTrackeriOSRegister_t m_AppTrackeriOSRegister;
    AppTrackeriOSUnRegister_t m_AppTrackeriOSUnRegister;
    AppTrackeriOS_startSession_t m_AppTrackeriOS_startSession;
    AppTrackeriOS_closeSession_t m_AppTrackeriOS_closeSession;
    AppTrackeriOS_event_t m_AppTrackeriOS_event;
    AppTrackeriOS_eventWithValue_t m_AppTrackeriOS_eventWithValue;
    AppTrackeriOS_loadModule_t m_AppTrackeriOS_loadModule;
    AppTrackeriOS_loadModuleToCache_t m_AppTrackeriOS_loadModuleToCache;
    AppTrackeriOS_destroyModule_t m_AppTrackeriOS_destroyModule;
    AppTrackeriOS_fixAdOrientation_t m_AppTrackeriOS_fixAdOrientation;
    AppTrackeriOS_setAgeRange_t m_AppTrackeriOS_setAgeRange;
    AppTrackeriOS_setGender_t m_AppTrackeriOS_setGender;
    AppTrackeriOS_isAdReady_t m_AppTrackeriOS_isAdReady;
} AppTrackeriOSFuncs;
